### ISSUE TITLE
Frozen Fields compatibility

### ISSUE THREAD

**Issue by kleinerpirat** [hgiesel/anki_collapsible_fields#1]
The indicators don't show and the fields are not collapsed when using the [Frozen Fields](https://ankiweb.net/shared/info/516643804) addon by Glutanimate.
The setting under "Fields" is visible though.

Using Anki Version 2.1.35 on Windows.

**Comment by TowelSniffer** [comment]
Just to add to this but the same problem persists with your own version of frozen fields, ze frozen fields, however, the icons show, they just don't work.

**Comment by hgiesel** [comment]
@kleinerpirat Glutanimate's Frozen Fields is incompatible with most add-ons that affect Editor functionality. Please use [Ze Frozen Fields](https://ankiweb.net/shared/info/94610912) instead, which is equal in functionality, only more compatible with other add-ons.

@TowelSniffer Can you make sure you updated Ze Frozen Fields? I pushed an update to Ze Frozen Fields before uploading Collapsible Fields. Maybe trigger the update over the Addons window in Anki.

**Comment by kleinerpirat** [comment]
Thank you @hgiesel for the support, it works perfectly with your version of frozen fields.
I'll close the issue.
