### ISSUE TITLE
Conflict with Frozen Fields

### ISSUE THREAD

**Issue by knvvs07** [hgiesel/anki_collapsible_fields#5]
using Anki 2.1.35

Installing Collapsible Fields + Frozen Fields causes a conflict:

- in the browser: both icons (CF arrow toggle + FF snowflake) disappear but keyboard shortcuts work
- in the add window: FF icon appears but CF icon does not.  CF keyboard shortcut does not work.

Disabling either add-on restores the functionality for the other.

**Comment by hgiesel** [comment]
Please use [Ze FrozenFields](https://ankiweb.net/shared/info/94610912#:~:text=Shift%2BF9%20%3A%20Toggle%20Frozen%20status,if%20no%20fields%20are%20frozen.) instead. It offers the same functionality as Frozen Fields, but is compatible with other add-ons.

**Comment by knvvs07** [comment]
Just installed and it looks like both are working together.  Thanks.
