### ISSUE TITLE
Anki 2.1.41 beta4-46e9720e: browser card focus weird/broken? behaviour

### ISSUE THREAD

**Issue by sandersantema** [hgiesel/anki_collapsible_fields#6]
### Steps to reproduce:
1. Open browser from main screen: ![image](https://user-images.githubusercontent.com/21057514/108743897-9945b480-7539-11eb-9744-918f13291fb5.png)
2. Click on a field of the card, here the focus is still correct (orange outline and non greyed out symbols): ![image](https://user-images.githubusercontent.com/21057514/108743990-b5e1ec80-7539-11eb-86b8-90b763482ff5.png)
3. Click on another card: ![image](https://user-images.githubusercontent.com/21057514/108756610-07de3e80-7549-11eb-8883-f9d921ccdcd1.png)
4. Clicking on a field does not properly focus it (orange outline but greyed out symbols), after which for instance the shortcut for clozes doesn't work: 
![image](https://user-images.githubusercontent.com/21057514/108756779-483dbc80-7549-11eb-8491-23b73181f9da.png)

It does focus properly after clicking on another field. I'm not quite certain whether this is a bug of Anki itself (i.e. caused by changes in editor/ browser code) or this addon, but it only occurs when I've got this plugin enabled. 

### Addons I'm currently using:
![image](https://user-images.githubusercontent.com/21057514/108758316-3c52fa00-754b-11eb-9c48-8c77f2c455a7.png)

### System information (might be a bit superfluous):
Operating System: openSUSE Tumbleweed 20210220
KDE Plasma Version: 5.21.0
KDE Frameworks Version: 5.79.0
Qt Version: 5.15.2
Kernel Version: 5.10.16-1-default
OS Type: 64-bit
Graphics Platform: X11
Processors: 8 × AMD Ryzen 7 PRO 3700U w/ Radeon Vega Mobile Gfx
Memory: 21.4 GiB of RAM
Graphics Processor: AMD Radeon™ Vega 10 Graphics

**Comment by hgiesel** [comment]
In fact this is a bug in Anki right now. I'm already close to a solution.

**Comment by sandersantema** [comment]
Ah very nice, so I suppose it's not necessary to open this issue on the anki repo?

**Comment by hgiesel** [comment]
I already opened my PR: https://github.com/ankitects/anki/pull/1037
